---
- hosts: k8s_kubectl

  tasks:
    - name: Check if KubeDNS service is already deployed
      shell: "kubectl get svc --namespace=kube-system kube-dns"
      register: kubectl
      failed_when: "not (('not found' in kubectl.stderr) or ('' in kubectl.stdout))"
      tags:
        - k8s-dns

    - name: Create deployment temporary deployment file for KubeDNS
      template:
        src: "templates/kubedns.yaml.j2"
        dest: "/tmp/kubedns.yaml"
        mode: 0600
      when: kubectl.rc == 1
      tags:
        - k8s-dns

    - name: Deploy the kube-dns cluster add-on (if needed)
      command: kubectl create -f /tmp/kubedns.yaml
      when: kubectl.rc == 1
      tags:
        - k8s-dns
    
    - name: Remove temporary KubeDNS deployment file
      file:
        path: "/tmp/kubedns.yaml"
        state: absent
      tags:
        - k8s-dns
