---
- hosts: k8s_kubectl

  tasks:
    - name: Create temporary deployment file for kube-router ClusterRole
      copy:
        content: "{{kube_router_clusterrole}}"
        dest: "/tmp/kube_router_clusterrole.yaml"
        mode: 0600
      tags:
        - kube-router-clusterrole

    - name: Deploy kube-router ClusterRole
      command: "kubectl apply -f /tmp/kube_router_clusterrole.yaml"
      tags:
        - kube-router-clusterrole
    
    - name: Remove temporary kube-router ClusterRole deployment file
      file:
        path: "/tmp/kube_router_clusterrole.yaml"
        state: absent
      tags:
        - kube-router-clusterrole

    - name: Create temporary deployment file for kube-router ClusterRoleBinding
      copy:
        content: "{{kube_router_clusterrolebinding}}"
        dest: "/tmp/kube_router_clusterrolebinding.yaml"
        mode: 0600
      tags:
        - kube-router-clusterrolebinding

    - name: Deploy kube-router ClusterRoleBinding
      command: "kubectl apply -f /tmp/kube_router_clusterrolebinding.yaml"
      tags:
        - kube-router-clusterrolebinding

    - name: Remove temporary kube-router ClusterRoleBinding deployment file
      file:
        path: "/tmp/kube_router_clusterrolebinding.yaml"
        state: absent
      tags:
        - kube-router-clusterrolebinding

    - name: Create temporary deployment file for kube-router ServiceAccount
      copy:
        content: "{{kube_router_serviceaccount}}"
        dest: "/tmp/kube_router_serviceaccount.yaml"
        mode: 0600
      tags:
        - kube-router-serviceaccount

    - name: Deploy kube-router ServiceAccount
      command: "kubectl apply -f /tmp/kube_router_serviceaccount.yaml"
      tags:
        - kube-router-serviceaccount

    - name: Remove temporary kube-router ServiceAccount deployment file
      file:
        path: "/tmp/kube_router_serviceaccount.yaml"
        state: absent
      tags:
        - kube-router-serviceaccount

    - name: Create temporary deployment file for kube-router DaemonSet
      copy:
        content: "{{kube_router_daemonset}}"
        dest: "/tmp/kube_router_daemonset.yaml"
        mode: 0600
      tags:
        - kube-router-daemonset

    - name: Deploy kube-router DaemonSet
      command: "kubectl apply -f /tmp/kube_router_daemonset.yaml"
      tags:
        - kube-router-daemonset

    - name: Remove temporary kube-router DaemonSet deployment file
      file:
        path: "/tmp/kube_router_daemonset.yaml"
        state: absent
      tags:
        - kube-router-daemonset
