---
- hosts: k8s_kubectl

  tasks:
    - name: Get IP address of first host in k8s_controller group and use as API server
      set_fact:
        apiServer: |
          {% set item = groups["k8s_controller"][0] %}
          {{ hostvars[item]["ansible_"+hostvars[item]["peervpn_conf_interface"]].ipv4.address }}
      tags:
        - kubernetes-ca

    - name: Remove newline from API server IP address
      set_fact:
        apiServer: "{{apiServer |replace('\n', '')}}"
      tags:
        - k8s-auth-config-proxy

    - name: Generate a kubeconfig file for the kube-proxy service (set-cluster)
      shell: "kubectl config set-cluster {{k8s_config_cluster_name}} --certificate-authority={{k8s_ca_conf_directory}}/ca-k8s-apiserver.pem --embed-certs=true --server=https://{{apiServer}}:6443 --kubeconfig={{k8s_config_directory}}/kube-proxy.kubeconfig"
      tags:
        - k8s-auth-config-proxy

    - name: Generate a kubeconfig file for the kube-proxy service (set-credentials)
      shell: "kubectl config set-credentials kube-proxy --client-certificate={{k8s_ca_conf_directory}}/cert-kube-proxy.pem --client-key={{k8s_ca_conf_directory}}/cert-kube-proxy-key.pem --embed-certs=true --kubeconfig={{k8s_config_directory}}/kube-proxy.kubeconfig"
      tags:
        - k8s-auth-config-proxy

    - name: Generate a kubeconfig file for the kube-proxy service (set-context)
      shell: "kubectl config set-context default --cluster={{k8s_config_cluster_name}} --user=kube-proxy --kubeconfig={{k8s_config_directory}}/kube-proxy.kubeconfig"
      tags:
        - k8s-auth-config-proxy

    - name: Set use-context
      shell: "kubectl config use-context default --kubeconfig={{k8s_config_directory}}/kube-proxy.kubeconfig"
      with_inventory_hostnames:
        - k8s_worker
      tags:
        - k8s-auth-config-proxy
