---
- name: Delete coredns service account
  local_action:
    module: k8s
    state: absent
    definition: "{{ lookup('template', 'templates/serviceaccount.yml.j2') | from_yaml }}"
  tags:
    - delete-serviceaccount

- name: Delete coredns ClusterRole
  local_action:
    module: k8s
    state: absent
    definition: "{{ lookup('template', 'templates/clusterrole.yml.j2') | from_yaml }}"
  tags:
    - delete-clusterrole

- name: Delete coredns ClusterRoleBinding
  local_action:
    module: k8s
    state: absent
    definition: "{{ lookup('template', 'templates/clusterrolebinding.yml.j2') | from_yaml }}"
  tags:
    - delete-clusterrolebinding

- name: Delete coredns ConfigMap
  local_action:
    module: k8s
    state: absent
    definition: "{{ lookup('template', 'templates/configmap.yml.j2') | from_yaml }}"
  tags:
    - delete-configmap

- name: Delete coredns Deployment
  local_action:
    module: k8s
    state: absent
    definition: "{{ lookup('template', 'templates/deployment.yml.j2') | from_yaml }}"
  tags:
    - delete-deployment

- name: Delete coredns Service
  local_action:
    module: k8s
    state: absent
    definition: "{{ lookup('template', 'templates/service.yml.j2') | from_yaml }}"
  tags:
    - delete-service
