---
- name: Run CoreDNS playbook
  hosts: localhost
  tasks:
    - name: Set default action
      set_fact:
        deploy_action: "install"
      tags:
        - always

    - name: Set default action
      set_fact:
        deploy_action: "delete"
      when: delete is defined
      tags:
        - always

    - include_tasks: "tasks/{{deploy_action|lower}}.yml"
      tags:
        - always
