---
- hosts: k8s_kubectl

  tasks:
    - name: Delete Traefik DaemonSet
      command: "kubectl delete daemonset --namespace=kube-system traefik-ingress-controller"
      tags:
        - traefik-daemonset

    - name: Delete secret
      shell: "kubectl delete secret --namespace=kube-system traefik-etcd"
      tags:
        - traefik-secret

    - name: Delete Traefik ClusterRoleBinding
      command: "kubectl delete clusterrolebinding --namespace=kube-system traefik-ingress-controller"
      tags:
        - traefik-clusterrolebinding

    - name: Delete Traefik ClusterRole
      command: "kubectl delete clusterrole --namespace=kube-system traefik-ingress-controller"
      tags:
        - traefik-clusterrole
    
    - name: Delete Traefik ServiceAccount
      command: "kubectl delete serviceaccount --namespace=kube-system traefik-ingress-controller"
      tags:
        - traefik-serviceaccount

    - name: Delete etcd /traefik/acme/account/lock key
      shell: |
        ETCDCTL_API=3 sudo -E {{etcd_bin_dir}}/etcdctl del /traefik/acme/account/lock \
          --endpoints=https://127.0.0.1:{{etcd_client_port}} \
          --cacert={{k8s_conf_dir}}/ca-etcd.pem \
          --cert={{k8s_conf_dir}}/cert-etcd.pem \
          --key={{k8s_conf_dir}}/cert-etcd-key.pem
      when: delete_keys is defined and delete_keys == "true"
      run_once: true
      delegate_to: "{{groups.k8s_etcd|first}}"
      tags:
        - traefik-etcd-key

    - name: Delete etcd /traefik/acme/account/object key
      shell: |
        ETCDCTL_API=3 sudo -E {{etcd_bin_dir}}/etcdctl del /traefik/acme/account/object \
          --endpoints=https://127.0.0.1:{{etcd_client_port}} \
          --cacert={{k8s_conf_dir}}/ca-etcd.pem \
          --cert={{k8s_conf_dir}}/cert-etcd.pem \
          --key={{k8s_conf_dir}}/cert-etcd-key.pem
      when: delete_keys is defined and delete_keys == "true"
      run_once: true
      delegate_to: "{{groups.k8s_etcd|first}}"
      tags:
        - traefik-etcd-key
