---
- hosts: k8s_kubectl

  tasks:
    - name: Delete Traefik DaemonSet
      command: "kubectl delete daemonset --namespace=kube-system traefik-ingress-controller"
      tags:
        - traefik-daemonset

    - name: Delete secret
      shell: "kubectl delete secret --namespace=kube-system traefik-etcd"
      tags:
        - traefik-secret

    - name: Delete Traefik ClusterRoleBinding
      command: "kubectl delete clusterrolebinding --namespace=kube-system traefik-ingress-controller"
      tags:
        - traefik-clusterrolebinding

    - name: Delete Traefik ClusterRole
      command: "kubectl delete clusterrole --namespace=kube-system traefik-ingress-controller"
      tags:
        - traefik-clusterrole
    
    - name: Delete Traefik ServiceAccount
      command: "kubectl delete serviceaccount --namespace=kube-system traefik-ingress-controller"
      tags:
        - traefik-serviceaccount

    - name: Delete etcd /traefik/acme/account/lock key
      shell: "ETCDCTL_API=3 {{etcd_bin_dir}}/etcdctl --endpoints=http://localhost:{{etcd_client_port}} del /traefik/acme/account/lock"
      when: delete_keys is defined and delete_keys == "true"
      run_once: true
      delegate_to: "{{groups.k8s_etcd|first}}"
      tags:
        - traefik-etcd-key

    - name: Delete etcd /traefik/acme/account/object key
      shell: "ETCDCTL_API=3 {{etcd_bin_dir}}/etcdctl --endpoints=http://localhost:{{etcd_client_port}} del /traefik/acme/account/object"
      when: delete_keys is defined and delete_keys == "true"
      run_once: true
      delegate_to: "{{groups.k8s_etcd|first}}"
      tags:
        - traefik-etcd-key
