---
- hosts: k8s_kubectl

  tasks:
    - name: Delete Traefik DaemonSet
      command: "kubectl delete daemonset --namespace=kube-system traefik-ingress-controller"
      tags:
        - traefik-daemonset

    - name: Delete secret
      shell: "kubectl delete secret --namespace=kube-system traefik-consul"
      tags:
        - traefik-secret

    - name: Delete Traefik ClusterRoleBinding
      command: "kubectl delete clusterrolebinding --namespace=kube-system traefik-ingress-controller"
      tags:
        - traefik-clusterrolebinding

    - name: Delete Traefik ClusterRole
      command: "kubectl delete clusterrole --namespace=kube-system traefik-ingress-controller"
      tags:
        - traefik-clusterrole
    
    - name: Delete Traefik ServiceAccount
      command: "kubectl delete serviceaccount --namespace=kube-system traefik-ingress-controller"
      tags:
        - traefik-serviceaccount
