---
- name: Delete DaemonSet
  k8s:
    state: absent
    definition: "{{ lookup('template', 'templates/daemonset.yml.j2') | from_yaml }}"
  delegate_to: localhost
  tags:
    - delete-daemonset

- name: Delete StatefulSet
  k8s:
    state: absent
    definition: "{{ lookup('template', 'templates/statefulset.yml.j2') | from_yaml }}"
  delegate_to: localhost
  tags:
    - delete-statefulset

- name: Delete ClusterRoleBinding
  k8s:
    state: absent
    definition: "{{ lookup('template', 'templates/clusterrolebinding.yml.j2') | from_yaml }}"
  delegate_to: localhost
  tags:
    - delete-clusterrolebinding

- name: Delete ClusterRole
  k8s:
    state: absent
    definition: "{{ lookup('template', 'templates/clusterrole.yml.j2') | from_yaml }}"
  delegate_to: localhost
  tags:
    - delete-clusterrole

- name: Delete ServiceAccount
  k8s:
    state: absent
    definition: "{{ lookup('template', 'templates/serviceaccount.yml.j2') | from_yaml }}"
  delegate_to: localhost
  tags:
    - delete-serviceaccount

- name: Delete StorageClass
  k8s:
    state: absent
    definition: "{{ lookup('template', 'templates/storageclass.yml.j2') | from_yaml }}"
  delegate_to: localhost
  tags:
    - delete-storageclass

- name: Delete CSIDriver CRD
  k8s:
    state: absent
    definition: "{{ lookup('template', 'templates/csidriver-crd.yml.j2') | from_yaml }}"
  delegate_to: localhost
  tags:
    - delete-csidriver-crd

- name: Delete hcloud-csi secret
  k8s:
    state: absent
    definition: "{{ lookup('template', 'templates/secret.yml.j2') | from_yaml }}"
  delegate_to: localhost
  tags:
    - delete-secret

- name: Delete Service for controller metrics
  k8s:
    state: absent
    definition: "{{ lookup('template', 'templates/service-controller-metrics.yml.j2') | from_yaml }}"
  delegate_to: localhost
  tags:
    - delete-service-controller-metrics

- name: Delete Service for node metrics
  k8s:
    state: absent
    definition: "{{ lookup('template', 'templates/service-node-metrics.yml.j2') | from_yaml }}"
  delegate_to: localhost
  tags:
    - delete-service-node-metrics

